name: Psalm

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'composer*'
      - 'psalm*'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-20.04
    timeout-minutes: 6
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - uses: actions/checkout@v3

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # the way cache keys are set up will always cause a cache miss
      # but will restore the cache generated during the previous run based on partial match
      - name: Retrieve Psalm’s cache
        uses: actions/cache@v3
        with:
          path: ./.cache/psalm
          key: ${{ runner.os }}-psalm-cache-${{ hashFiles('psalm.xml', 'psalm-baseline.xml', './composer.json') }}

      # mtime needs to be restored for Psalm cache to work correctly
      - name: Restore mtimes
        uses: chetan/git-restore-mtime-action@v1

      - name: Install composer dependencies
        run: |
          composer config --ansi -- http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_LICENSE_KEY }}
          composer update --prefer-dist --no-interaction --no-suggest --ansi

      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github
